# Generated by Django 6.0 on 2025-12-13 03:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='支持Markdown格式,图片、代码、视频', verbose_name='内容'),
        ),
    ]
