# Generated by Django 6.0 on 2025-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_background',
            field=models.ImageField(blank=True, null=True, upload_to='site_bg/', verbose_name='自定义背景图(覆盖主题色)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='theme_color',
            field=models.CharField(choices=[('blue', '☁️ 天空之城 (默认天蓝)'), ('purple', '🔮 赛博朋克 (霓虹紫)'), ('dark', '🌙 深夜模式 (极简黑)'), ('green', '🍃 森之秘境 (清新绿)')], default='blue', max_length=20, verbose_name='博客主题风格'),
        ),
    ]
