# Generated by Django 6.0 on 2025-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_site_background_sitesetting_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_bg',
            field=models.ImageField(blank=True, null=True, upload_to='user_bg/', verbose_name='个人背景图'),
        ),
        migrations.AddField(
            model_name='user',
            name='blog_title',
            field=models.CharField(default='我的个人空间', max_length=50, verbose_name='个人博客标题'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(choices=[('blue', '☁️ 天空之城 (默认天蓝)'), ('purple', '🔮 赛博朋克 (霓虹紫)'), ('dark', '🌙 深夜模式 (极简黑)'), ('green', '🍃 森之秘境 (清新绿)'), ('pink', '🌸 樱花烂漫 (柔和粉)')], default='blue', max_length=20, verbose_name='主题风格'),
        ),
    ]
