# Generated by Django 6.0 on 2025-12-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_blog_bg_user_blog_title_user_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_live2d',
            field=models.BooleanField(default=True, verbose_name='显示看板娘'),
        ),
    ]
